### ISSUE TITLE
arfur-sys build error

### ISSUE THREAD

**Issue by AngleSideAngle** [arfur-rs/arfur#9] opened 2022-08-22 01:20 UTC
Upon running `cargo build`, `arfur-sus/build.rs` throws the following error: `/tmp/arfur-sys.An5Jc6SRSMsv/target/include/hal/HAL.h:7:10: fatal error: 'stdint.h' file not found`.

Note that this error does not occur when running `clang HAL.h` manually.

This is on Fedora 36 with all necessary dependencies installed.
I was able to replicate this behavior inside an Ubuntu Server LTS vm with clang and openssl-devel installed.

I'm not exactly sure what is causing this issue, but I think it might be related to lines 257-8 in `arfur-sys/build.rs` (maybe).
```rs
let bindings = bindgen::Builder::default()
  ...
  .clang_arg("-nostdinc")
  .clang_arg("-nostdinc++")
  ...
```
Removing them resulted in different errors.
Considering I have not read docs for `bindgen` or used c++ before, this likely is not even an issue.

**Comment by bobbbay** [comment] 2022-08-29 03:19
The issue is, unfortunately, your development environment. Out of curiosity, if you try to build the crate without those two lines, what errors do you get?

**Comment by bobbbay** [comment] 2022-09-15 11:32
@AngleSideAngle after support for CI, I have a few clear steps for getting a development environment. Simply run the following on Ubuntu:

```
sudo apt-get install -y gcc-arm-linux-gnueabi pkg-config libssl-dev libc++-dev clang
```

I'm not familiar with Fedora, but as long as you find the equivalent packages it should work. Let me know how it goes!

Oh, and be sure to pull the newest commits.

P.S. alternatively, you can install Nix and enter the development environment through there.

**Comment by bobbbay** [comment] 2022-11-04 18:54
@AngleSideAngle is this still an issue? Arfur now is opt-in for bindgen, so you should be able to use the pre-generated bindings without the above setup. Please let me know if I can close this :).

**Comment by bobbbay** [comment] 2022-11-13 23:55
Closing due to probable resolution and inactivity.

**Closed by bobbbay** 2022-11-13 23:55 UTC
